version: 2.1

orbs:
  python: circleci/python@1.2

workflows:
  test-build-md:  # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run. 
    # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows 
    jobs:
      - build-and-test:
          filters:
            branches:
              only: master

jobs:
  build-and-test: 
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: pip install
          command: |
              pip install notion
      - run:
          name: Run tests
          command: |
              python -m unittest test.notion_ci_test.NotionCiTest.test_generate_markdown_showcase 
              build/NotionDown/draft/markdown_test_page.md
      - run:
          name: Dump outputs
          command: |
              echo "Generated MD file:\n"
              cat build/NotionDown/*/markdown_test_page.md
